    - name: Installing ufw in Ubuntu
      apt:
        name: ufw
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Installing firewalld on CentOS
      yum:
        name: firewalld
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Enabling SSH access in CentOS
      ansible.builtin.firewalld:
        port: 22/tcp
        permanent: true
        state: enabled
      when: ansible_distribution == 'CentOS'

    - name: Enabling HTTP accessin CentOS
      ansible.builtin.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
      when: ansible_distribution == 'CentOS'

    - name: Enabling HTTPS accessin CentOS
      ansible.builtin.firewalld:
        port: 443/tcp
        permanent: true
        state: enabled
      when: ansible_distribution == 'CentOS'

    - name: Configuring the firewall rules in Ubuntu
      ansible.builtin.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.protocol }}"
      loop: "{{ firewall_port_proto }}"
      when: ansible_os_family == "Debian"
