    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update yum cache
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install security updates
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"

    - name: Install security updates
      yum:
        security: yes
      when: ansible_os_family == "RedHat"
